/* Capturas estáveis da versão final; não altera dados científicos. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pw=require(process.env.SIAB_PLAYWRIGHT_MODULE||'playwright'),out=path.join(__dirname,'results');
(async()=>{const {server,url}=await require('./server.cjs').start(),b=await pw.chromium.launch({headless:true,args:['--no-sandbox']});const c=await b.newContext({viewport:{width:1366,height:768},reducedMotion:'reduce'}),p=await c.newPage(),shots=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(8000);await c.addInitScript(()=>{localStorage.setItem('siab_abertura','off');localStorage.setItem('siab_inicializacao','"inicio"');localStorage.setItem('siab_manual_visto','true')});
const go=async r=>{await p.evaluate(r=>SIAB.irPara('#/'+r),r);await p.waitForFunction(r=>SIAB.rota.nome===r.split('/')[0],r)};
async function shot(name,fullPage=false){await p.waitForFunction(()=>!document.getElementById('toast')||document.getElementById('toast').hidden);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(out,name+'.png'),fullPage,animations:'disabled'});shots.push({name,viewport:p.viewportSize(),fullPage});}
try{
 await p.goto(url);await p.waitForFunction(()=>document.documentElement.dataset.appPronto==='true');await p.evaluate(()=>A11Y.definir('theme','light'));
 for(const r of ['inicio','aprender','missoes','roteiros','montagens','manual','professor']){await go(r);await shot('rc5-'+r,true)}
 await go('laboratorio');await p.evaluate(()=>SIAB.montarMontagem('titulacao-forte'));await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');await p.evaluate(()=>{SIAB.workspace.close('left');SIAB.workspace.close('right')});await shot('rc5-bancada-desktop');
 for(const [launch,name]of[['workspace-montagem','montagem'],['workspace-ver','ver'],['workspace-dados','dados']]){await p.click('#'+launch);await shot('rc5-'+name);await p.keyboard.press('Escape')}
 await p.click('#menu-btn');await shot('rc5-menu-desktop');await p.keyboard.press('Escape');
 await p.evaluate(()=>SIAB.gaveta.projetor(true));await shot('rc5-projetor');await p.evaluate(()=>SIAB.gaveta.projetor(false));
 await p.evaluate(()=>SIAB.tour.iniciar());await shot('rc5-tour');await p.keyboard.press('Escape');
 await p.evaluate(()=>A11Y.definir('theme','dark'));await shot('rc5-tema-escuro');await p.evaluate(()=>A11Y.definir('contrast',true));await shot('rc5-alto-contraste');await p.evaluate(()=>{A11Y.definir('contrast',false);A11Y.definir('theme','light')});
 await p.evaluate(()=>{SIAB.instrumentos.medir(SIAB.current(),'fita');SIAB.relatorios.capturar()});await go('relatorio');
 for(const[mode,name]of[['completo','completo'],['mao','mao'],['analise','analise']]){await p.selectOption('#report-mode',mode);await shot('rc5-relatorio-'+name,true);await p.evaluate(()=>SIAB.relatorios.preparar());await p.pdf({path:path.join(out,'rc5-relatorio-'+name+'.pdf'),format:'A4',printBackground:true});await p.evaluate(()=>document.body.classList.remove('imprimindo','imprimindo-folha'))}
 const t=await p.evaluate(async()=>{const m=SIAB.montagens.find(m=>m.id==='tres-indicadores');return SIAB.atividades.codificar({schema:2,tipo:'montagem',item:m.id,modulo:m.nivel,temperatura:25,instrumentos:['indicador','fita','phmetro'],navegacao:'restrita',identificacao:{nome:'Estudante',turma:'Investigação'}})});await go('atividade/'+t);await p.locator('#atividade-iniciar button').click();await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');await p.evaluate(()=>SIAB.instrumentos.medir(SIAB.current(),'fita'));await p.click('#activity-exit');await shot('rc5-encerrar-com-dados');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio');await go('caderno');await shot('rc5-caderno-pratica',true);await p.click('[data-practice-data]');await p.waitForSelector('.practice-vessel');await shot('rc5-caderno-pratica-dados',true);
 await go('laboratorio');await p.evaluate(()=>SIAB.montarMontagem('titulacao-forte'));await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');
 for(const[w,h]of[[320,568],[360,800],[390,844],[414,896]]){await p.setViewportSize({width:w,height:h});await p.evaluate(()=>{SIAB.workspace.close('left');SIAB.workspace.close('right');SIAB.render(true);document.getElementById('focus-view').scrollTop=0});await shot('mobile-'+w+'-bancada');}
 await p.setViewportSize({width:390,height:844});
 for(const[launch,name]of[['workspace-montagem','montagem'],['workspace-ver','medir'],['workspace-dados','dados']]){await p.click('#'+launch);if(name==='medir'){await p.click('[data-ver-family=medir]');await p.click('#tab-ph')}await shot('mobile-'+name);await p.keyboard.press('Escape')}
 await p.click('#menu-btn');await shot('rc5-menu-mobile');await p.keyboard.press('Escape');
 await p.setViewportSize({width:1366,height:900});await go('manual');const zoomSession=await c.newCDPSession(p);await zoomSession.send('Emulation.setDeviceMetricsOverride',{width:683,height:450,deviceScaleFactor:2,mobile:false});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('rc5-zoom-200',true);await zoomSession.send('Emulation.clearDeviceMetricsOverride');await p.setViewportSize({width:1366,height:900});
 await p.goto(url+'/docs/ICONOGRAFIA-RC5.html');await shot('rc5-iconografia',true);await p.click('#theme');await shot('rc5-iconografia-escura',true);await p.click('#expand');assert.equal(await p.locator('#expand').getAttribute('aria-expanded'),'true');
 assert.deepEqual(errors,[]);assert.ok(shots.length>=24);fs.writeFileSync(path.join(out,'evidencias-rc5.json'),JSON.stringify({version:'1.0.0-rc.5',date:new Date().toISOString(),browser:b.version(),shots,errors,zoom:'Emulação de zoom 200%: viewport CSS 683×450 e escala 2 para tela 1366×900; zoom nativo em aparelho permanece externo'},null,2)+'\n');console.log('Capturas',shots.length,'Erros',errors.length);
}finally{await b.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
