/* DOM integration checks. Does not claim pixel layout or native dialog QA. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.SIAB_JSDOM_MODULE||'jsdom');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'https://siab.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,doc=w.document;
let mobile=true;
const listeners=[];
w.matchMedia=()=>({get matches(){return mobile;},addEventListener:(_,fn)=>listeners.push(fn)});
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'));};
const $=id=>doc.getElementById(id),click=id=>$(id).click();
const change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));};
const submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
try{
  for(const el of doc.querySelectorAll('script[src]'))w.eval(fs.readFileSync(path.join(root,el.getAttribute('src')),'utf8'));
  const s=w.SIAB.state;
  assert.equal(s.tubes.length,3);assert.equal($('workspace').hidden,true);
  click('start-btn');assert.equal($('workspace').hidden,false);assert.equal($('ph-value').textContent,'2,00');
  for(let i=0;i<20;i++)click('drop-btn');
  assert.equal($('ph-value').textContent,'7,00');assert.equal($('color-name').textContent,'verde');assert.match($('equivalence-note').textContent,/equivalência/);
  click('rename-btn');$('new-name').value='Amostra <ácido> & teste';submit('rename-form');
  assert.equal($('tube-name').textContent,'Amostra <ácido> & teste');assert.equal($('tube-name').children.length,0);
  click('next-btn');assert.equal(s.activeId,2);assert.equal($('ph-value').textContent,'2,00');
  click('previous-btn');assert.equal($('ph-value').textContent,'7,00');assert.equal(w.SIAB.current().additions.length,20);
  click('undo-btn');assert.equal(w.SIAB.current().additions.length,19);
  click('overview-tab');assert.equal($('controls').hidden,true);assert.equal(doc.querySelectorAll('.overview-tube').length,3);
  doc.querySelector('.overview-tube[data-tube="1"]').click();assert.equal(s.view,'focus');
  click('prepare-btn');assert.equal($('controls').inert,false);assert.equal($('experiment').inert,true);
  click('close-controls');assert.equal($('experiment').inert,false);assert.equal($('controls').inert,true);
  click('compare-btn');click('confirm-yes');assert.equal(s.tubes.length,6);
  const group=w.SIAB.targets(w.SIAB.current());assert.equal(group.length,3);
  click('drop-btn');assert.ok(group.every(t=>t.additions.length===20));assert.equal($('ph-value').textContent,'7,00');
  click('ph-toggle');assert.equal($('ph-value').textContent,'—');assert.equal($('equivalence-note').textContent,'');
  click('prepare-btn');change('solution-select','acetic');$('concentration').value='.01';submit('prepare-form');click('confirm-yes');
  assert.ok(group.every(t=>t.solution==='acetic'&&t.additions.length===0));assert.equal($('experiment').inert,false);
  const old=w.SIAB.current().initialVolume;$('initial-volume').value='-1';submit('prepare-form');assert.equal(w.SIAB.current().initialVolume,old);
  $('initial-volume').value='1';click('ph-toggle');
  const id=s.activeId;mobile=false;listeners.forEach(fn=>fn());assert.equal(s.activeId,id);assert.equal($('controls').inert,false);
  mobile=true;listeners.forEach(fn=>fn());assert.equal(s.activeId,id);assert.equal($('controls').inert,true);
  click('access-btn');change('theme-select','light');assert.equal(doc.documentElement.dataset.theme,'light');
  change('theme-select','contrast');assert.equal(doc.documentElement.dataset.contrast,'on');
  for(let i=0;i<10;i++)click('font-plus');assert.equal(w.A11Y.estado.fontScale,2);assert.ok(doc.documentElement.classList.contains('large-text'));
  $('access-dialog').close();
  while(s.tubes.length<10)doc.querySelector('[data-action="add"]').click();
  assert.ok([...doc.querySelectorAll('[data-action="add"]')].every(x=>x.disabled));
  assert.ok($('compare-btn').disabled);click('close-controls');
  click('prepare-btn');click('remove-btn');click('confirm-yes');assert.equal(s.tubes.length,9);assert.ok(w.SIAB.current());
  console.log('Fluxos DOM: iniciar, titular, desfazer, renomear, navegar, visão geral, painel, comparar, preparar grupo, validar entradas, trocar largura, acessibilidade, limite e remoção: OK');
}finally{w.close();}
