/* Atualização real RC.4.5 → RC.5. SIAB_BASELINE_DIR deve apontar à base extraída. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const pw=require(process.env.SIAB_PLAYWRIGHT_MODULE||'playwright'),root=path.resolve(__dirname,'..'),base=process.env.SIAB_BASELINE_DIR;
if(!base||!fs.existsSync(path.join(base,'sw.js')))throw new Error('Informe SIAB_BASELINE_DIR com o projeto RC.4.5 extraído.');
const out=path.join(__dirname,'results'),result={version:'1.0.0-rc.5',date:new Date().toISOString(),engines:[]};let served=path.resolve(base),offline=false;
const server=http.createServer((req,res)=>{if(offline)return req.socket.destroy();const name=decodeURIComponent(req.url.split('?')[0]),file=path.resolve(served,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(served+path.sep)){res.writeHead(403);return res.end()}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end()}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'application/octet-stream');res.end(data)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;try{
for(const engine of (process.env.SIAB_TEST_ENGINES||'chromium,firefox,webkit').split(',')){
 served=path.resolve(base);offline=false;const b=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox']}:{env:{...process.env,MOZ_DISABLE_CONTENT_SANDBOX:'1'}})}),ctx=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
 await ctx.addInitScript(()=>{localStorage.setItem('siab_abertura','off');localStorage.setItem('siab_inicializacao','"inicio"');localStorage.setItem('siab_manual_visto','true')});let p=await ctx.newPage();p.setDefaultTimeout(12000);
 const e={engine,version:b.version(),cases:[],errors:[],assets:[]};result.engines.push(e);p.on('pageerror',x=>e.errors.push(x.message));const ready=()=>p.waitForFunction(()=>document.documentElement.dataset.appPronto==='true');
 async function test(name,fn){try{await fn();e.cases.push({name,status:'OK'});console.log(engine,'OK',name)}catch(x){e.cases.push({name,status:'Falha',error:x.stack});console.log(engine,'FAIL',name,x.message)}fs.writeFileSync(path.join(out,'offline-rc5.json'),JSON.stringify(result,null,2)+'\n')}
 let before;
 await test('RC.4.5 real: cache instalado e sessão com medições',async()=>{await p.goto(url);await ready();assert.equal(await p.evaluate(()=>SIAB.version),'1.0.0-rc.4.5');await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>!!navigator.serviceWorker.controller);const t=await p.evaluate(async()=>{const m=SIAB.montagens.find(m=>m.id==='tres-indicadores');return SIAB.atividades.codificar({schema:2,tipo:'montagem',item:m.id,modulo:m.nivel,temperatura:25,instrumentos:['indicador','fita','phmetro'],navegacao:'restrita',relatorio:'impresso'})});await p.evaluate(t=>SIAB.irPara('#/atividade/'+t),t);await p.locator('#atividade-iniciar button').click();await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');await p.evaluate(()=>SIAB.instrumentos.medir(SIAB.current(),'fita'));before=await p.evaluate(()=>SIAB.state.tubes.map(t=>({id:t.id,raw:SIAB.instrumentos.raw(t)})));await p.reload();await ready();await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio')});
 await test('Atualização RC.5 remove cache anterior e preserva contexto/dados',async()=>{served=root;await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update()});await p.waitForFunction(async()=>{const k=await caches.keys();return k.some(x=>x.endsWith('siab-1.0.0-rc.5'))&&!k.some(x=>x.endsWith('siab-1.0.0-rc.4.5'))});await p.waitForSelector('#pwa-recarregar');await p.click('#pwa-recarregar');await ready();await p.waitForFunction(()=>SIAB.version==='1.0.0-rc.5');assert.deepEqual(await p.evaluate(()=>SIAB.state.tubes.map(t=>({id:t.id,raw:SIAB.instrumentos.raw(t)}))),before);assert.equal(await p.evaluate(()=>SIAB.ActivityContext.restricted()),true)});
 await test('Recursos cacheados coincidem byte a byte com RC.5',async()=>{e.assets=await p.evaluate(async()=>{const key=(await caches.keys()).find(x=>x.endsWith('siab-1.0.0-rc.5')),c=await caches.open(key);return Promise.all((await c.keys()).map(async req=>({url:new URL(req.url).pathname,hash:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await c.match(req)).arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('')})))});assert.ok(e.assets.length>=80);for(const a of e.assets){const file=path.join(root,a.url==='/'?'index.html':a.url.slice(1));assert.equal(a.hash,crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),a.url)}});
 await test('Reabrir página sem rede: áreas essenciais, experimento, relatório e recarga',async()=>{await p.click('#activity-exit');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio');await p.close();offline=true;if(engine==='chromium')await ctx.setOffline(true);e.networkIsolation=engine!=='chromium'?'Servidor indisponível: conexões encerradas; rede opcional bloqueada':'Contexto offline e servidor indisponível';await ctx.route('https://**/*',r=>r.abort());p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',x=>e.errors.push(x.message));await p.goto(url);await ready();assert.equal(await p.evaluate(()=>SIAB.version),'1.0.0-rc.5');for(const r of ['inicio','laboratorio','manual','montagens','roteiros','professor','caderno']){await p.evaluate(r=>SIAB.irPara('#/'+r),r);await p.waitForFunction(r=>SIAB.rota.nome===r,r);assert.ok(await p.locator('[data-tela="'+await p.evaluate(r=>SIAB.telas[r].secao,r)+'"]').isVisible(),r)}await p.evaluate(()=>{SIAB.irPara('#/laboratorio');SIAB.montarMontagem('titulacao-forte')});await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');await p.click('#drop-btn');await p.evaluate(()=>SIAB.instrumentos.medir(SIAB.current(),'fita'));assert.equal(await p.evaluate(()=>SIAB.current().additions.length),1);await p.evaluate(()=>SIAB.irPara('#/relatorio'));await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');await p.locator('[data-report-field=observacoes]').fill('Registro inteiramente offline');await p.reload();await ready();assert.equal(await p.locator('[data-report-field=observacoes]').inputValue(),'Registro inteiramente offline');await p.evaluate(()=>SIAB.irPara('#/professor'));await p.waitForFunction(()=>SIAB.rota.nome==='professor');await p.locator('#prof-form [type=submit]').click();await p.waitForFunction(()=>SIAB.persistencia.ler('siab_atividades_criadas',[]).length>0);await p.screenshot({path:path.join(out,'rc5-offline-'+engine+'.png')})});
 await test('Sem exceções não tratadas na atualização/offline',async()=>assert.deepEqual(e.errors,[]));offline=false;await ctx.close();await b.close();
}
}finally{await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'offline-rc5.json'),JSON.stringify(result,null,2)+'\n')}if(result.engines.some(e=>e.cases.some(c=>c.status!=='OK')))process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
