const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const pw=require(process.env.SIAB_PLAYWRIGHT_MODULE||'playwright'),Axe=require(process.env.SIAB_AXE_MODULE||'@axe-core/playwright').default;
const out=path.join(__dirname,'results'),result={version:'1.0.0-rc.5',date:new Date().toISOString(),engines:[]};
(async()=>{const {server,url}=await require('./server.cjs').start();try{
for(const engine of (process.env.SIAB_TEST_ENGINES||'chromium,firefox,webkit').split(',')){
 const b=await pw[engine].launch({headless:true,...(engine==='chromium'?{args:['--no-sandbox']}:{env:{...process.env,MOZ_DISABLE_CONTENT_SANDBOX:'1'}})});
 const entry={engine,version:b.version(),cases:[],errors:[],accessibility:[],geometry:[]};result.engines.push(entry);let ctx,p;
 const ready=()=>p.waitForFunction(()=>document.documentElement.dataset.appPronto==='true');
 async function fresh(standalone=false,block=false){await ctx?.close();ctx=await b.newContext({viewport:{width:1366,height:768},reducedMotion:'reduce',serviceWorkers:block?'block':'allow'});await ctx.addInitScript(()=>{try{localStorage.setItem('siab_abertura','off');localStorage.setItem('siab_manual_visto','true');if(!localStorage.getItem('siab_inicializacao'))localStorage.setItem('siab_inicializacao','"inicio"')}catch{}});p=await ctx.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>entry.errors.push(e.message));await p.goto(standalone?pathToFileURL(path.join(__dirname,'../SIAB-standalone.html')).href:url);await ready()}
 async function go(r){await p.evaluate(r=>SIAB.irPara('#/'+r),r);await p.waitForFunction(r=>SIAB.rota.nome===r.split('/')[0],r);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))}
 async function test(name,fn){try{await fn();entry.cases.push({name,status:'OK'});console.log(engine,'OK',name)}catch(e){entry.cases.push({name,status:'Falha',error:e.stack});console.log(engine,'FAIL',name,e.message);await p?.screenshot({path:path.join(out,engine+'-rc5-falha-'+entry.cases.length+'.png')}).catch(()=>{})}fs.writeFileSync(path.join(out,'rc5.json'),JSON.stringify(result,null,2)+'\n')}
 const shot=async(name,fullPage=false)=>{if(engine==='chromium')await p.screenshot({path:path.join(out,'rc5-'+name+'.png'),fullPage,animations:'disabled'})};
 const notes=()=>p.evaluate(()=>SIAB.progresso.dados.caderno.filter(n=>n.tipo==='pratica'));
 const measure=()=>p.evaluate(()=>{SIAB.instrumentos.medir(SIAB.current(),'fita');SIAB.atividades.salvarSessao()});
 const start=async()=>{await p.locator('#atividade-iniciar button').click();await p.waitForFunction(()=>['laboratorio','missao'].includes(SIAB.rota.nome))};
 const exit=async()=>{await p.click('#activity-exit');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio')};
 async function token(tipo,legacy){return p.evaluate(async({tipo,legacy})=>{const item=tipo==='montagem'?SIAB.montagens.find(m=>m.id==='tres-indicadores'):tipo==='roteiro'?SIAB.experimentos[0]:SIAB.missoes[0];return SIAB.atividades.codificar({schema:2,tipo,item:item.id,titulo:'Prática RC.5 · '+tipo,modulo:item.modulo||item.bancada?.nivel||item.nivel||'explorar',temperatura:25,instrumentos:SIAB.atividades.instrumentos,navegacao:'restrita',identificacao:{nome:'Estudante de teste',turma:'Homologação'},...(legacy?{relatorio:legacy}:{})})},{tipo,legacy})}
 for(const tipo of ['montagem','roteiro','missao']){let t,id,old;
  await test(tipo+': sem dados, confirmação segura e preferência preservada',async()=>{await fresh();t=await token(tipo);await go('atividade/'+t);await start();assert.equal(await p.evaluate(()=>SIAB.atividades.temDados()),false);await p.evaluate(()=>SIAB.persistencia.salvar('siab_inicializacao','laboratorio'));await p.click('#activity-exit');assert.equal(await p.locator('#confirm-extra').isVisible(),false);assert.equal(await p.evaluate(()=>document.activeElement.id),'confirm-cancel');await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>!!SIAB.atividades.ativa));await exit();assert.equal((await notes()).length,0);assert.equal(await p.evaluate(()=>SIAB.persistencia.ler('siab_inicializacao')),'laboratorio')});
  await test(tipo+': retomar, continuar ou abrir relatório antes de encerrar',async()=>{await go('atividade/'+t);await p.waitForSelector('[data-session-continue]');assert.match(await p.locator('.session-choice').innerText(),/Continuar sessão[\s\S]*Iniciar nova sessão/);await p.click('[data-session-continue]');await p.waitForFunction(()=>['laboratorio','missao'].includes(SIAB.rota.nome));id=await p.evaluate(()=>SIAB.atividades.ativa.sessionId);await measure();await p.click('#activity-exit');assert.equal(await p.locator('#confirm-cancel').innerText(),'Continuar atividade');await p.click('#confirm-cancel');await p.click('#activity-exit');await p.click('#confirm-extra');await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');assert.equal(await p.locator('#relatorio-print').innerText(),'Imprimir / Salvar como PDF');assert.equal(await p.locator('#relatorio-baixar').count(),0);await p.locator('[data-report-field=observacoes]').fill('Observação preservada · '+tipo);await p.click('#relatorio-encerrar');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio');assert.equal((await notes()).length,1);assert.equal((await notes())[0].sessaoId,id)});
  await test(tipo+': Caderno estruturado sem alterar bancada livre',async()=>{const before=await p.evaluate(()=>JSON.stringify(SIAB.state));await go('caderno');await p.click('[data-practice-data]');await p.waitForSelector('.practice-vessel');const text=await p.locator('#caderno-lista').innerText();for(const s of ['Condições iniciais','Medições registradas','Condições finais'])assert.ok(text.includes(s),s);assert.equal(await p.evaluate(()=>JSON.stringify(SIAB.state)),before);await shot('caderno-pratica-dados',true);await p.locator('#caderno-lista a[href^="#/relatorio/"]').click();await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');assert.equal(await p.locator('[data-report-field=observacoes]').inputValue(),'Observação preservada · '+tipo);await p.click('#relatorio-voltar');await p.waitForFunction(()=>SIAB.rota.nome==='caderno')});
  await test(tipo+': finalizar diretamente no relatório, sem duplicar prática',async()=>{await go('atividade/'+t);await p.click('[data-session-continue]');await p.waitForFunction(()=>['laboratorio','missao'].includes(SIAB.rota.nome));await p.reload();await ready();await p.waitForFunction(()=>['laboratorio','missao'].includes(SIAB.rota.nome));assert.equal(await p.evaluate(()=>SIAB.atividades.ativa.sessionId),id);if(tipo==='missao')await p.evaluate(()=>{SIAB.motor.ativa.respostas.conclusao='Conclusão da investigação';SIAB.atividades.salvarSessao()});await p.click('#activity-finish');await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');assert.equal(await p.evaluate(()=>SIAB.atividades.ativa.etapa),'finalizada');if(tipo==='missao')assert.equal(await p.evaluate(()=>SIAB.relatorios.atual.respostasMissao.conclusao),'Conclusão da investigação');await p.click('#relatorio-encerrar');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio');assert.equal((await notes()).length,1);assert.equal((await notes())[0].estadoPratica,'Finalizada');old=await p.evaluate(id=>SIAB.relatorios.obter(id),id);assert.ok(old.recipientes.some(t=>t.rawMeasurements.some(m=>m.tecnica==='fita')))});
  await test(tipo+': nova tentativa separa dados e mantém relatório anterior',async()=>{await go('atividade/'+t);await p.waitForSelector('[data-session-continue]');assert.match(await p.locator('.session-choice').innerText(),/Ver relatório anterior[\s\S]*Iniciar nova tentativa/);await shot('reabertura-finalizada');await p.click('[data-session-continue]');await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');assert.equal(await p.evaluate(()=>SIAB.relatorios.atual.id),id);await p.click('#relatorio-voltar');await p.waitForFunction(()=>SIAB.rota.nome==='atividade');await p.click('[data-session-new]');await p.click('#confirm-cancel');assert.equal(await p.evaluate(()=>SIAB.atividades.ativa.sessionId),id);await p.click('[data-session-new]');await p.click('#confirm-yes');await start();assert.notEqual(await p.evaluate(()=>SIAB.atividades.ativa.sessionId),id);assert.equal(await p.evaluate(()=>SIAB.state.tubes.flatMap(t=>SIAB.instrumentos.raw(t)).filter(m=>m.tecnica!=='indicador').length),0);await measure();await exit();const n=await notes();assert.equal(n.length,2);assert.equal(new Set(n.map(x=>x.sessaoId)).size,2);const r=await p.evaluate(id=>SIAB.relatorios.obter(id),id);assert.deepEqual(r.recipientes,old.recipientes);assert.deepEqual(r.aluno,old.aluno);await go('caderno');await shot('caderno-pratica',true)});
 }
 await test('Links antigos digital/impresso aceitos sem seletor no Professor',async()=>{await go('professor');assert.equal(await p.locator('#prof-form [name=relatorio]').count(),0);for(const legacy of ['digital','impresso']){const t=await token('montagem',legacy);await go('atividade/'+t);await start();await measure();await p.click('#activity-finish');await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');await p.click('#relatorio-encerrar');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio')}});
 await test('Sessão não finalizada: nova sessão preserva a prática anterior',async()=>{await fresh();const t=await token('montagem');await go('atividade/'+t);await start();await measure();const id=await p.evaluate(()=>SIAB.atividades.ativa.sessionId);await exit();const old=await p.evaluate(id=>SIAB.relatorios.obter(id),id);await go('atividade/'+t);await p.click('[data-session-new]');await p.click('#confirm-yes');await start();assert.notEqual(await p.evaluate(()=>SIAB.atividades.ativa.sessionId),id);assert.equal(await p.evaluate(()=>SIAB.state.tubes.flatMap(t=>SIAB.instrumentos.raw(t)).filter(m=>m.tecnica!=='indicador').length),0);await measure();await exit();assert.equal((await notes()).length,2);assert.deepEqual((await p.evaluate(id=>SIAB.relatorios.obter(id),id)).recipientes,old.recipientes)});
 await test('22 símbolos próprios e biblioteca única no mobile e accordion',async()=>{const r=await p.evaluate(()=>{const keys=['home','learn','mission','protocol','lab','notebook','manual','mount','professor','accessibility','settings','projector','tour','report','history','table','setup','prepare','eye','ruler','chart','data'];return{paths:keys.map(k=>SIAB.icons.paths[k]),nav:[...document.querySelectorAll('.bottom-nav [data-icon]')].map(x=>({name:x.dataset.icon,d:x.querySelector('path').getAttribute('d')})),library:SIAB.icons.paths}});assert.equal(new Set(r.paths).size,22);assert.ok(r.nav.length>=4);for(const i of r.nav)assert.equal(i.d,r.library[i.name]);await go('manual/relatorios');await p.locator('[data-manual-expand]').first().click();assert.equal(await p.locator('[data-manual-expand]').first().getAttribute('aria-expanded'),'true');assert.equal(await p.locator('[data-manual-expand] .disclosure-icon').first().getAttribute('data-icon'),'dropdown')});
 await test('Apagar prática: cancelamento e remoção isolada do registro',async()=>{await go('caderno');const before=await notes();await p.locator('[data-apagar-nota]').first().click();assert.ok((await p.locator('#confirm-yes').getAttribute('class')).includes('danger-btn'));await p.click('#confirm-cancel');assert.equal((await notes()).length,before.length);await p.locator('[data-apagar-nota]').first().click();await p.click('#confirm-yes');assert.equal((await notes()).length,before.length-1);assert.ok(await p.evaluate(id=>SIAB.relatorios.obter(id),before[0].relatorioId))});
 await test('Quiet-btn global e axe nas telas públicas, Caderno, relatório e Sobre',async()=>{for(const r of ['inicio','aprender','missoes','roteiros','montagens','caderno','professor','manual','relatorio']){await go(r);const bad=await p.locator('.quiet-btn:visible').evaluateAll(els=>els.map(e=>({text:e.textContent.trim(),h:e.getBoundingClientRect().height,b:getComputedStyle(e).borderTopWidth,r:getComputedStyle(e).borderRadius,d:getComputedStyle(e).textDecorationLine})).filter(x=>x.h<43.9||parseFloat(x.b)<1||parseFloat(x.r)<1||x.d.includes('underline')));assert.deepEqual(bad,[],r);const a=await new Axe({page:p}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();entry.accessibility.push({route:r,violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});assert.deepEqual(a.violations.map(v=>v.id),[],r);await shot(r,true)}await p.evaluate(()=>document.getElementById('about-dialog').showModal());await shot('sobre');const a=await new Axe({page:p}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();entry.accessibility.push({route:'sobre',violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});assert.deepEqual(a.violations.map(v=>v.id),[]);await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('#about-dialog')));await p.keyboard.press('Shift+Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('#about-dialog')));await p.keyboard.press('Escape')});
 await test('Dez viewports: docas, geometria, proporções e mobile',async()=>{await go('laboratorio');await p.evaluate(()=>SIAB.montarMontagem('titulacao-forte'));await p.waitForFunction(()=>SIAB.rota.nome==='laboratorio');for(const[w,h]of[[320,568],[360,800],[390,844],[414,896],[768,1024],[1024,768],[1280,720],[1366,768],[1440,900],[1920,1080]]){await p.setViewportSize({width:w,height:h});await p.evaluate(()=>{SIAB.workspace.close('left');SIAB.workspace.close('right');SIAB.state.view='focus';SIAB.render(true)});const g=await p.evaluate(()=>{const box=id=>{const e=document.getElementById(id),r=e.getBoundingClientRect(),s=getComputedStyle(e);return{id,x:r.x,right:r.right,width:r.width,height:r.height,radius:s.borderRadius,padding:s.padding,margin:s.marginLeft}};return{viewport:[innerWidth,innerHeight],overflow:document.documentElement.scrollWidth>innerWidth+1,controls:['agitar-btn','workspace-quick-measure','undo-btn','drop-btn','mobile-doses-toggle'].map(box)}});entry.geometry.push(g);assert.equal(g.overflow,false);if(w<=414){const[a,m]=g.controls;assert.equal(a.height,m.height);assert.ok(Math.abs(a.width-m.width)<=2);assert.equal(a.radius,m.radius);assert.equal(a.padding,m.padding);assert.equal(a.margin,'0px');for(const c of g.controls){assert.ok(c.height>=44,c.id);assert.ok(c.x>=-1&&c.right<=w+1,c.id)}assert.ok(g.controls[2].width>=44&&g.controls[2].width<=48);assert.ok(g.controls[4].width>=72);await shot('mobile-'+w+'-bancada');for(const[launcher,name]of[['workspace-montagem','montagem'],['workspace-ver','ver'],['workspace-dados','dados']]){await p.click('#'+launcher);await shot('mobile-'+w+'-'+name);await p.keyboard.press('Escape')}}else await shot('bancada-'+w)}});
 await test('Enter, Space, Escape, foco, anúncio, rotação e texto 200%',async()=>{await p.setViewportSize({width:390,height:844});await p.locator('#workspace-montagem').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#workspace-montagem').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'workspace-montagem');await p.locator('#workspace-ver').focus();await p.keyboard.press('Space');await p.keyboard.press('Escape');await measure();await p.waitForFunction(()=>document.getElementById('announcer').textContent.includes('pH'));await p.setViewportSize({width:844,height:390});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await go('professor');await p.setViewportSize({width:390,height:400});const field=p.locator('#prof-form [name=titulo]');await field.fill('Teclado emulado');await field.scrollIntoViewIfNeeded();const r=await field.boundingBox();assert.ok(r.y>=0&&r.y+r.height<=400);await p.evaluate(()=>A11Y.definir('fontScale',2));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('texto-200');await p.evaluate(()=>A11Y.definir('fontScale',1))});
 await test('VLibras: falha de rede e de inicialização não bloqueiam aplicativo',async()=>{await fresh(false,true);let requests=0;await ctx.route('https://vlibras.gov.br/**',r=>{requests++;return r.abort()});assert.equal(requests,0);await p.evaluate(()=>{const e=document.getElementById('libras-check');e.checked=true;e.dispatchEvent(new Event('change'))});await p.waitForFunction(()=>document.getElementById('toast').textContent.includes('VLibras não pôde'));assert.equal(await p.locator('#vlibras-widget').count(),0);assert.ok(requests>0);await ctx.unroute('https://vlibras.gov.br/**');await ctx.route('https://vlibras.gov.br/**',r=>r.fulfill({contentType:'application/javascript',body:'window.VLibras={Widget:class{constructor(){throw new Error("Serviço indisponível")}}}'}));await p.evaluate(()=>document.getElementById('libras-check').dispatchEvent(new Event('change')));await p.waitForFunction(()=>!document.getElementById('vlibras-script'));await go('manual');assert.ok(await p.locator('[data-tela=manual]').isVisible())});
 await test('Standalone: catálogo e ciclo com tentativas independentes',async()=>{await fresh(true);assert.equal(await p.evaluate(()=>SIAB.version),'1.0.0-rc.5');assert.equal(await p.evaluate(()=>Object.keys(SIAB.solutions).length),140);const t=await token('montagem');await go('atividade/'+t);await start();await measure();const id=await p.evaluate(()=>SIAB.atividades.ativa.sessionId);await p.click('#activity-finish');await p.waitForFunction(()=>SIAB.rota.nome==='relatorio');await p.click('#relatorio-encerrar');await p.click('#confirm-yes');await p.waitForFunction(()=>SIAB.rota.nome==='inicio');assert.equal((await notes()).length,1);await go('atividade/'+t);await p.click('[data-session-new]');await p.click('#confirm-yes');await start();assert.notEqual(await p.evaluate(()=>SIAB.atividades.ativa.sessionId),id);assert.equal(await p.evaluate(()=>SIAB.state.tubes.flatMap(t=>SIAB.instrumentos.raw(t)).filter(m=>m.tecnica!=='indicador').length),0);assert.ok(await p.evaluate(id=>SIAB.relatorios.obter(id),id))});
 await test('Nenhum erro de execução não tratado',async()=>assert.deepEqual(entry.errors,[]));await ctx.close();await b.close();
}
}finally{await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'rc5.json'),JSON.stringify(result,null,2)+'\n')}
if(result.engines.some(e=>e.cases.some(c=>c.status!=='OK')||e.errors.length))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
